import { describe, expect, it } from 'vitest'
import {
  buildDefaultProjectMetadata,
  buildInitialProjectSnapshot,
  buildPersistedProjectMeta,
  buildPersistedProjectSnapshot,
  clampProjectGridZoom,
  getFirstContentPage,
  isDefaultProjectMetadata,
  isProjectTrashed,
  normalizeProjectTitle,
  resolveMetadataDirtyFlag,
  resolveOutlineTreeForHydration,
} from '@/domains/workspace/application/project-session.service'
import type { ProjectMeta } from '@/shared/infrastructure/db'

describe('project-session.service', () => {
  it('normalizes title and trash state', () => {
    expect(normalizeProjectTitle(undefined)).toBe('Untitled Project')
    expect(normalizeProjectTitle('  A  ')).toBe('A')
    expect(isProjectTrashed({ id: 'p', title: 'x', pageCount: 0, updatedAt: 0, createdAt: 0 })).toBe(
      false,
    )
    expect(
      isProjectTrashed({
        id: 'p',
        title: 'x',
        pageCount: 0,
        updatedAt: 0,
        createdAt: 0,
        trashedAt: Date.now(),
      }),
    ).toBe(true)
  })

  it('builds default metadata and initial snapshot', () => {
    const metadata = buildDefaultProjectMetadata({
      projectTitle: 'My Project',
      defaultAuthor: '  Alice  ',
    })
    const snapshot = buildInitialProjectSnapshot({ zoom: 1.25, metadata })

    expect(metadata).toEqual({
      title: 'My Project',
      author: 'Alice',
      subject: '',
      keywords: [],
    })
    expect(snapshot.historyPointer).toBe(-1)
    expect(snapshot.zoom).toBe(1.25)
    expect(snapshot.metadata?.author).toBe('Alice')
  })

  it('clamps zoom and resolves first content page', () => {
    expect(clampProjectGridZoom(-100)).toBe(120)
    expect(clampProjectGridZoom(999)).toBe(320)

    const first = getFirstContentPage([
      { id: 'd1', isDivider: true },
      { id: 'p1', sourceFileId: 's1', sourcePageIndex: 0, rotation: 0 },
    ])
    expect(first?.id).toBe('p1')
  })

  it('builds persisted meta/snapshot values', () => {
    const existingMeta: ProjectMeta = {
      id: 'p1',
      title: 'Old',
      pageCount: 1,
      createdAt: 10,
      updatedAt: 10,
      trashedAt: null,
    }

    const nextMeta = buildPersistedProjectMeta({
      existingMeta,
      title: 'New',
      pageCount: 3,
      now: 42,
      thumbnail: undefined,
    })

    const snapshot = buildPersistedProjectSnapshot({
      activeSourceIds: ['s1'],
      pageMap: [{ id: 'p1', sourceFileId: 's1', sourcePageIndex: 0, rotation: 0 }],
      history: [],
      historyPointer: 0,
      zoom: 1,
      outlineTree: [],
      outlineDirty: false,
      metadata: { title: 'Doc', author: '', subject: '', keywords: [] },
      security: undefined,
      metadataDirty: false,
      ignoredPreflightRuleIds: [],
    })

    expect(nextMeta.title).toBe('New')
    expect(nextMeta.pageCount).toBe(3)
    expect(nextMeta.updatedAt).toBe(42)
    expect(snapshot.historyPointer).toBe(0)
    expect(snapshot.activeSourceIds).toEqual(['s1'])
  })

  it('resolves metadata dirty and hydration outline behavior', () => {
    expect(
      isDefaultProjectMetadata({ title: 'Untitled Project', author: '', subject: '', keywords: [] }),
    ).toBe(true)
    expect(
      resolveMetadataDirtyFlag({
        metadata: { title: 'Untitled Project', author: '', subject: '', keywords: [] },
      }),
    ).toBe(false)
    expect(
      resolveMetadataDirtyFlag({
        metadata: { title: 'Custom', author: '', subject: '', keywords: [] },
      }),
    ).toBe(true)

    const restored = resolveOutlineTreeForHydration({
      persistedOutlineTree: [{ id: 'n1', parentId: null, title: 'A', expanded: true, dest: { type: 'none' }, children: [] }],
      outlineDirty: true,
      autoGeneratedOutline: [{ id: 'auto', parentId: null, title: 'Auto', expanded: true, dest: { type: 'none' }, children: [] }],
    })
    expect(restored[0]?.id).toBe('n1')

    const auto = resolveOutlineTreeForHydration({
      persistedOutlineTree: [],
      outlineDirty: false,
      autoGeneratedOutline: [{ id: 'auto', parentId: null, title: 'Auto', expanded: true, dest: { type: 'none' }, children: [] }],
    })
    expect(auto[0]?.id).toBe('auto')
  })
})
